<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\components\core\Leistd.Core\Leistd.Core.csproj" />
    <ProjectReference Include="..\..\components\auditing\Leistd.Auditing.Core\Leistd.Auditing.Core.csproj" />
    <ProjectReference Include="..\..\components\event-bus\Leistd.EventBus.Core\Leistd.EventBus.Core.csproj" />
  </ItemGroup>

</Project>