<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\components\realtime\Leistd.RealTime.Core\Leistd.RealTime.Core.csproj" />
    <ProjectReference Include="..\..\..\..\components\realtime\Leistd.RealTime.AspNetCore.SignalR\Leistd.RealTime.AspNetCore.SignalR.csproj" />
    <ProjectReference Include="..\..\..\shared\Leistd.TestBase\Leistd.TestBase.csproj" />
  </ItemGroup>

</Project>
