<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\components\security\Leistd.Security.AspNetCore\Leistd.Security.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\..\components\security\Leistd.Security.Core\Leistd.Security.Core.csproj" />
  </ItemGroup>

</Project>
