<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../components/security/Leistd.Security.OpenIddict.Server/Leistd.Security.OpenIddict.Server.csproj" />
  </ItemGroup>
</Project>
