<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
<!--#if (OpenIddictServer)-->
    <PackageReference Include="OpenIddict.Abstractions" />
<!--#endif-->
<!--#if (IncludeLocalization)-->
    <!-- 权限定义的显示名按请求 culture 在响应阶段翻译，需要本地化抽象。 -->
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
<!--#endif-->
  </ItemGroup>

  <!-- Leistd 框架引用 -->
  <ItemGroup>
    <PackageReference Include="Leistd.ObjectMapping.Mapster" />
    <PackageReference Include="Leistd.Security.Core" />
    <PackageReference Include="Leistd.Authorization.Core" />
    <PackageReference Include="Leistd.Settings.Core" />
    <PackageReference Include="Leistd.MultiTenancy.Core" />
    <PackageReference Include="Leistd.Lock.Core" />
    <PackageReference Include="Leistd.Ddd.Domain" />
    <PackageReference Include="Leistd.Ddd.Application" />
    <PackageReference Include="Leistd.Ddd.Application.Contracts" />
    <PackageReference Include="Leistd.UnitOfWork.Core" />
  </ItemGroup>

  <!-- 业务项目内部引用 -->
  <ItemGroup>
    <ProjectReference Include="..\CompanyName.ProjectName.Domain\CompanyName.ProjectName.Domain.csproj" />
  </ItemGroup>

</Project>
