import type { Translation } from 'primeng/api';

export const PRIMENG_ZH_CN: Translation = {
  startsWith: '开头是',
  contains: '包含',
  notContains: '不包含',
  endsWith: '结尾是',
  equals: '等于',
  notEquals: '不等于',
  noFilter: '无筛选',
  lt: '小于',
  lte: '小于或等于',
  gt: '大于',
  gte: '大于或等于',
  is: '是',
  isNot: '不是',
  before: '早于',
  after: '晚于',
  clear: '清除',
  apply: '应用',
  matchAll: '匹配全部',
  matchAny: '匹配任意',
  addRule: '添加规则',
  removeRule: '移除规则',
  accept: '是',
  reject: '否',
  choose: '选择',
  upload: '上传',
  cancel: '取消',
  dayNames: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
  dayNamesShort: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
  dayNamesMin: ['日', '一', '二', '三', '四', '五', '六'],
  monthNames: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
  monthNamesShort: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
  dateFormat: 'yy-mm-dd',
  firstDayOfWeek: 1,
  today: '今天',
  weekHeader: '周',
  weak: '弱',
  medium: '中',
  strong: '强',
  passwordPrompt: '请输入密码',
  emptyMessage: '暂无数据',
  emptyFilterMessage: '没有匹配结果',
  pending: '处理中'
};
