<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\components\object-mapping\Leistd.ObjectMapping.Core\Leistd.ObjectMapping.Core.csproj" />
    <ProjectReference Include="..\Leistd.Ddd.Application.Contracts\Leistd.Ddd.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
