services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      # 生产环境
      - ASPNETCORE_ENVIRONMENT=Production
  db-migrator:
    build:
      context: ..
      dockerfile: Dockerfile
      target: migrator
