<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\components\email\Leistd.Email.Smtp\Leistd.Email.Smtp.csproj" />
    <ProjectReference Include="..\..\..\shared\Leistd.TestBase\Leistd.TestBase.csproj" />
  </ItemGroup>

</Project>
